# Generated by Django 4.2.7 on 2023-12-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='About name')),
                ('description', models.TextField(verbose_name='About description')),
                ('button_name', models.CharField(max_length=20, verbose_name='Button name')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Blog name')),
                ('description', models.TextField(verbose_name='Blog description')),
            ],
        ),
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Blog name')),
                ('description', models.TextField(verbose_name='Blog description')),
                ('date', models.DateField(verbose_name='Blog date')),
                ('button_name', models.CharField(max_length=20, verbose_name='Button name')),
                ('image', models.ImageField(upload_to='', verbose_name='Blog image')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Class name')),
                ('description', models.TextField(verbose_name='Class description')),
            ],
        ),
        migrations.CreateModel(
            name='ClassImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Class name')),
                ('button_name', models.CharField(max_length=20, verbose_name='Button name')),
                ('image', models.ImageField(upload_to='', verbose_name='Class image')),
                ('icon_image', models.ImageField(upload_to='', verbose_name='Icon image')),
            ],
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('location', models.CharField(max_length=70, verbose_name='Location')),
                ('logo', models.ImageField(upload_to='', verbose_name='Logo')),
                ('main_name_first', models.CharField(max_length=30, verbose_name='Main name first')),
                ('main_name_second', models.CharField(max_length=30, verbose_name='Main name second')),
                ('name_first', models.CharField(max_length=30, verbose_name='Name first')),
                ('name_second', models.CharField(max_length=30, verbose_name='Name second')),
                ('button_name', models.CharField(max_length=20, verbose_name='Button name')),
            ],
        ),
    ]
